service: event-guru-backend

package:
  exclude:
    - src/bin/ffmpeg_mac
    - src/bin/ffmpeg_win.exe
    - test

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: eu-west-1
  memorySize: 512
  cfLogs: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - '*'

resources:
  Resources:
    EventGuruEventsCacheTable:
          Type: 'AWS::DynamoDB::Table'
          DeletionPolicy: Retain
          Properties:
            AttributeDefinitions:
              -
                AttributeName: location
                AttributeType: S
            KeySchema:
              -
                AttributeName: location
                KeyType: HASH
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
            TableName: event-guru-event-caches

    EventGuruBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: event-guru-store
        AccessControl: PublicReadWrite
        CorsConfiguration:
          CorsRules:
          - AllowedMethods:
              - GET
            AllowedOrigins:
              - http://ask-ifr-download.s3.amazonaws.com
              - https://eventguru.io

    EventGuruBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: EventGuruBucket
        PolicyDocument:
          Statement:
            - Action:
                - 's3:GetObject'
              Effect: Allow
              Principal: '*'
              Resource:
                Fn::Join:
                  - ''
                  - - 'arn:aws:s3:::'
                    - Ref: EventGuruBucket
                    - '/*'

functions:
  events-rest-api:
    handler: src/lambda/handler.getEvents
    events:
      - http:
          path: events
          method: get
          request:
            parameters:
              querystrings:
                location: true
                page: true
                pageSize: false

  # Cron job to preload events
  events-preload:
    handler: events/events-preload.run
    description: Event Guru - Event cron preloader
    timeout: 300
    events:
      - schedule: cron(1 0 * * ? *) # 00:01 every midnight

  # EMail bounce and complaint handling
  email-bounce-handler:
    handler: mail/aws-ses-notifications.handler
    description: Event Guru - Email bounce handler
    events:
      - sns: email-bounces
      - sns: email-complaints
      - sns: email-deliveries
