service: alexa-skill-event-guru

package:
  exclude:
    - bin/ffmpeg_mac
    - bin/ffmpeg_win.exe
    - test

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: eu-west-1
  memorySize: 512
  cfLogs: true
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
        - "ses:SendRawEmail"
      Resource:
        - '*'

resources:
  Resources:
    Mp3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: event-guru-store
        AccessControl: PublicReadWrite
        CorsConfiguration:
          CorsRules:
          - AllowedMethods:
              - GET
            AllowedOrigins:
              - http://ask-ifr-download.s3.amazonaws.com

    Mp3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: Mp3Bucket
        PolicyDocument:
          Statement:
            - Action:
                - 's3:GetObject'
              Effect: Allow
              Principal: '*'
              Resource:
                Fn::Join:
                  - ''
                  - - 'arn:aws:s3:::'
                    - Ref: Mp3Bucket
                    - '/*'

functions:
  # Alexa
  alexaSkill:
    handler: alexa/skill.handler
    description: Alexa skill to listen to concerts nearby
    events:
      - alexaSkill
